### ISSUE TITLE
User reported java.lang.Error: Watchdog with Clutter mod clutter-1.20.1-0.3.9.jar

### ISSUE THREAD

**Issue by gamerpotion** [EmilsGithub/Clutter-Mod-Repository#14]
hi, a user of our darkrpg serverpack reported a crash on their server (log below).  When clutter mod was removed the crash went away. Please can you look into this

Full log - https://pastebin.com/a8d3Lykh

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-07-29 21:33:43
Description: Watching Server

java.lang.Error: Watchdog
	at java.base@17.0.8/java.util.ImmutableCollections$SetN.probe(ImmutableCollections.java:1017)
	at java.base@17.0.8/java.util.ImmutableCollections$SetN.contains(ImmutableCollections.java:938)
	at net.minecraft.class_6880$class_6883.method_40220(class_6880.java:184)
	at net.minecraft.class_4970$class_4971.method_26164(class_4970.java:1182)
	at net.minecraft.class_14.method_58(class_14.java:570)
	at net.minecraft.class_6.method_17(class_6.java:294)
	at net.minecraft.class_14.method_64(class_14.java:429)
	at net.minecraft.class_6.method_25(class_6.java:264)
	at net.minecraft.class_14.method_29302(class_14.java:480)
	at net.minecraft.class_14$$Lambda$14972/0x00007f0431aa1000.get(Unknown Source)
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.computeIfAbsent(Long2ObjectOpenHashMap.java:448)
	at net.minecraft.class_14.method_29303(class_14.java:480)
	at net.minecraft.class_14.method_63(class_14.java:476)
	at net.minecraft.class_6.method_47893(class_6.java:71)
	at net.minecraft.class_6.method_21(class_6.java:60)
	at net.minecraft.class_13.method_52(class_13.java:43)
	at net.minecraft.class_1408.method_18416(class_1408.java:207)
	at net.minecraft.class_1408.method_35142(class_1408.java:179)
	at net.minecraft.class_1408.method_6348(class_1408.java:156)
	at net.emilsg.clutter.entity.custom.ButterflyEntity$ButterflyWanderAroundGoal.method_6269(ButterflyEntity.java:285)
	at net.minecraft.class_4135.method_6269(class_4135.java:41)
	at net.minecraft.class_1355.method_6275(class_1355.java:107)
	at net.minecraft.class_1308.method_6023(class_1308.java:771)
	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at net.minecraft.class_1308.method_6007(class_1308.java:550)
	at net.minecraft.class_1296.method_6007(class_1296.java:128)
	at net.minecraft.class_1429.method_6007(class_1429.java:58)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_3218$$Lambda$14885/0x00007f0431a89480.accept(Unknown Source)
	at net.minecraft.class_1937.mixinextras$bridge$0$accept(class_1937.java)
	at net.minecraft.class_1937$$Lambda$14886/0x00007f0431a896b8.call(Unknown Source)
	at net.minecraft.class_1937.wrapOperation$ccg000$neruina$catchTickingEntities(class_1937.java:3066)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_3218$$Lambda$14855/0x00007f0431a7c9f0.accept(Unknown Source)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at net.minecraft.server.MinecraftServer$$Lambda$13050/0x00007f0431784508.run(Unknown Source)
	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)```

**Comment by EmilsGithub** [comment]
Hi, it's an error with the way Butterfly pathfinding is handled, it's a known issue and should be fixed in the next update.

**Comment by gamerpotion** [comment]
> Hi, it's an error with the way Butterfly pathfinding is handled, it's a known issue and should be fixed in the next update.

hi, thanks for the update. Do you have an ETA on the next update? so I can also plan modpack update around it

**Comment by EmilsGithub** [comment]
Not really since I don't want to stress it but I'd say in a week or two. Maybe earlier if everything currently planned for the update goes smoothly.

**Comment by EmilsGithub** [comment]
FYI, 0.4.0 Releasing later today.
