### ISSUE TITLE
SulphurBlock crash

### ISSUE THREAD

**Issue by MetaForge** [EmilsGithub/Clutter-Mod-Repository#17]
Seems to be some kind of issue with the SulphurBlock. It crashes the server when I try to enter the nether 🤷‍♂️ any assistance appreciated. I need that kiwi in my server 😄

[19:33:33] [Worker-Main-38/ERROR]: Failed to light chunk [32, -29]
java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[server-intermediary.jar:?]
        at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
        at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
        at net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: net.minecraft.class_148: Feature placement
        at net.minecraft.class_3898.method_17225(class_3898.java:701) ~[server-intermediary.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
        at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
        ... 11 more
Caused by: java.lang.ClassCastException: class net.minecraft.class_3233 cannot be cast to class net.minecraft.class_1937 (net.minecraft.class_3233 and net.minecraft.class_1937 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6f7fd0e6)
        at net.emilsg.clutter.block.custom.SulphurBlock.method_9559(SulphurBlock.java:25) ~[clutter-1.20-0.4.2.jar:?]
        at net.minecraft.class_4970$class_4971.method_26191(class_4970.java:1149) ~[server-intermediary.jar:?]
        at net.minecraft.class_3499.method_15173(class_3499.java:363) ~[server-intermediary.jar:?]
        at net.minecraft.class_251.method_1061(class_251.java:233) ~[server-intermediary.jar:?]
        at net.minecraft.class_251.method_1046(class_251.java:202) ~[server-intermediary.jar:?]
        at net.minecraft.class_3499.method_20532(class_3499.java:354) ~[server-intermediary.jar:?]
        at net.minecraft.class_3499.method_15172(class_3499.java:323) ~[server-intermediary.jar:?]
        at org.betterx.bclib.api.v2.levelgen.structures.StructureNBT.generateCentered(StructureNBT.java:69) ~[bclib-3.0.13.jar:?]
        at org.betterx.bclib.api.v2.levelgen.structures.StructureWorldNBT.generate(StructureWorldNBT.java:102) ~[bclib-3.0.13.jar:?]
        at org.betterx.bclib.api.v2.levelgen.structures.StructureWorldNBT.generateIfPlaceable(StructureWorldNBT.java:96) ~[bclib-3.0.13.jar:?]
        at org.betterx.bclib.api.v3.levelgen.features.features.TemplateFeature.method_13151(TemplateFeature.java:36) ~[bclib-3.0.13.jar:?]
        at net.minecraft.class_3031.method_40163(class_3031.java:166) ~[server-intermediary.jar:?]
        at net.minecraft.class_2975.method_12862(class_2975.java:28) ~[server-intermediary.jar:?]
        at net.minecraft.class_6796.method_39646(class_6796.java:54) ~[server-intermediary.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.SpinedBuffer$1Splitr.forEachRemaining(SpinedBuffer.java:356) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at net.minecraft.class_6796.method_39648(class_6796.java:53) ~[server-intermediary.jar:?]
        at net.minecraft.class_6796.method_39650(class_6796.java:42) ~[server-intermediary.jar:?]
        at net.minecraft.class_2794.method_12102(class_2794.java:357) ~[server-intermediary.jar:?]
        at net.minecraft.class_2806.method_51375(class_2806.java:108) ~[server-intermediary.jar:?]
        at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[server-intermediary.jar:?]
        at net.minecraft.class_2806.method_12154(class_2806.java:252) ~[server-intermediary.jar:?]
        at net.minecraft.class_3898.method_17225(class_3898.java:684) ~[server-intermediary.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
        at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
        ... 11 more

**Comment by EmilsGithub** [comment]
Got this error too, I will release a new version within a couple of minutes. 😄
