### ISSUE TITLE
Possible Conflict With "Better Third Person"?

### ISSUE THREAD

**Issue by Gambleesonia** [EmilsGithub/Clutter-Mod-Repository#27]
Hello! Thank you for the fantastic mod. I'm having an odd client crash when attempting to turn on the Tall Lamp Block. According to the crash report it looks like "Better Third Person" might be having a conflict with it? Any thoughts?

`---- Minecraft Crash Report ----
// Shall we play a game?
 
Time: 2023-08-23 18:09:08
Description: Unexpected error
 
java.lang.IllegalArgumentException: Cannot get property class_2754{name=half, clazz=class net.minecraft.class_2756, values=[upper, lower]} as it does not exist in Block{minecraft:air}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.emilsg.clutter.block.custom.TallLampBlock.method_9534(TallLampBlock.java:59)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133)
	at net.minecraft.class_636.method_41934(class_636.java:347)
	at net.minecraft.class_636.method_41933(class_636.java:324)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:323)
	at net.minecraft.class_310.method_1583(class_310.java:1802)
	at net.minecraft.class_310.redirect$boa000$betterthirdperson$onDoItemUse(class_310.java:10586)
	at net.minecraft.class_310.method_1508(class_310.java:2052)
	at net.minecraft.class_310.method_1574(class_310.java:1883)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.emilsg.clutter.block.custom.TallLampBlock.method_9534(TallLampBlock.java:59)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133)
	at net.minecraft.class_636.method_41934(class_636.java:347)
	at net.minecraft.class_636.method_41933(class_636.java:324)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:323)
	at net.minecraft.class_310.method_1583(class_310.java:1802)
	at net.minecraft.class_310.redirect$boa000$betterthirdperson$onDoItemUse(class_310.java:10586)
	at net.minecraft.class_310.method_1508(class_310.java:2052)`

**Comment by EmilsGithub** [comment]
What version of the mod are you running?
(Minecraft and mod version)
